### ISSUE TITLE
FYI; QX1 works with RX100 mk3 setting

### ISSUE THREAD

**Issue by Deph0** [ThibaudM/timelapse-sony#22]
Hi, just wanted to let anybody else that found this, that the DSC-ILCE-QX1 work with DSC-RX100M3 settings, this is because it is using the same ip and api as the RX100 mk3.

To the developer; you really 'ought to be using the sony-dev camera api if you want to continue this amazing app for discovery of the models. (dubbed "SSDP (Simple Service Discovery Protocol)" by sony)

Useful urls: 
https://developer.sony.com/develop/cameras/
https://github.com/erik-smit/sony-camera-api 

oh and- would love to have this as a desktop app, there's so much easier to use when doing timelapses indoor.

**Comment by ThibaudM** [comment]
Hi Deph0 and thank you for your comment,

The sony dev camera api doesn't support the only camera I have: RX100 mk2. And I think this is the case for some others, you can compare the list of supported devices with [this one](https://developer.sony.com/develop/cameras/device-support/). This is mostly due to the SSDP response which answers a bad address. See [this topic](https://camera.developer.sony.com/common/forum/en/viewtopic.php?f=21&t=121&start=10#p361) for more information.
I am also aware that it is painful to choose the device when a service can do it.

You don't really need an app for desktop, you just need to connect your computer to the camera via Wifi, then send this curl request in a loop:
`curl -X POST -d "{\"method\":\"actTakePicture\",\"params\":[],\"id\":1,\"version\":\"1.0\"}" http://10.0.0.1:10000/camera`, where `http://10.0.0.1:10000/camera` is the camera API address.

Thibaud

**Comment by Deph0** [comment]
Ah, i see. How annoying.

A full fledged app is easier to use and appeals to more people whom isn't inclined to use or learn the developer side of things. That is mostly why it would be nice, not really for myself- but for others.

**Comment by Deph0** [comment]
fixed in commit 9757c1e17717414a9cd9ccdcb82447af0e37b843 AFAIK.
