### ISSUE TITLE
Sony QX1 Not Working

### ISSUE THREAD

**Issue by JoshKoh** [ThibaudM/timelapse-sony#31]
There is no camera option for QX1 but I connected using QX30 as model. However, I can't take pictures and although the time lapse runs, no picture is taken with error message showing up "skipped due to unknown error".

**Comment by Deph0** [comment]
use the latest version of the app, it was added in v3.0.1

**Comment by ThibaudM** [comment]
The QX1 should be present in the list.
About the error, maybe it came from #29 

@Deph0, in [devices.xml](app/src/main/res/raw/devices.xml) QX1 is wrote as `QX1`

**Comment by Deph0** [comment]
On further inspection of this, it appears that the app complains about not being able to receive instructions from/to the camera, and frames may have been skipped due to not being able to send information to the device. 

the app works as expected, and the photos end up on the internal memory as it takes photos, despite the warning/error about skipping frames. (tested with latest playstore version, v3.0.1, 2017-jun-03)

@JoshKoh if you cannot find the device in the list, i suggest hitting the reload button next to the list on the startscreen.
