### ISSUE TITLE
Sony Alpha A6000 Support

### ISSUE THREAD

**Issue by RoyiAvital** [ThibaudM/timelapse-sony#4]
Hi,
This is great application.
Could you please add Sony Alpha A6000 support?

Thank You.

**Comment by supermarcos** [comment]
Hello, I recently acquired the same camera (Alpha 6000). Do I need to buy/install the time-lapse application from the sony store or your application does the same job (or similar) so I won't need it?
Thanks!
P.S: I agree with surf33, you should consider donations!

**Comment by retracked** [comment]
Hi,

this application does a similar job as the official one with slight differences. While you can automatically generate a movie out of the pictures with Sonys app, with this app you have no limitation of the picture number (990 with Sonys app) but only get the pictures - no movie.

Just watch one of the many Youtube reviews of Sonys timelapse app to see what the further differences are.

**Comment by supermarcos** [comment]
I must be doing something wrong... even though the app finds the camera on the network, the next steps are disabled and I can't go any further from the first screen of the app.
The app is installed in a sansum galaxy s2 i9100. I go to the "send to smartphone" option in the camera and activate, also, le wifi. It asks me for the password and I can put it and it seems to be connected, but it is not doing anything else, I can't go to the next step, it is still disabled. The app looks fine, it doesn't freeze or exits unexpectly, but it doesn't activate any other option.
Am I doing something wrong?
Thank you!

**Comment by ThibaudM** [comment]
Hi supermarcos,

Can you do a Screenshot when you have no option to continue ?

**Comment by retracked** [comment]
It is not this apps fault.

You have to use the appropriate app on your A6000, supermarcos. The "send to smartphone" option is not the correct one. Go to "applications" in your camera menu and download the "Smart Remote" app from www.playmemoriescameraapps.com. Afterwards start the just downloaded app and you may now connect your smartphone to your camera.

**Comment by retracked** [comment]
On some cameras the "Smart Remote" app is already installed. If you experience any problems with it make sure it is the newest version you are using. There was an update in november 2014.

**Comment by supermarcos** [comment]
Hello, again!
You're absolutely right. Sorry, my fault. I was connected to my wi-fi instead to the camera and, also, I was using the wrong option in my camera... I'm really sorry for waste your time. 
Thank you very much for helping a dumb like me.

BTW: where is supose the taken pictures will go? To the phone or in the SD? I tried one and appeared a message like "the function is not available in this camera" or something like that in the camera and at the end of the process in the app, I couldn't find any picture, neither in the phone, nor in the camera, so I guess I, again, did something wrong... any idea?

**Comment by supermarcos** [comment]
OK, now I figured out what was the problem. With certain shooting modes the remote control doesn't work, so it is necessary to set the camera shooting mode in the correct one. Once this is done, everything works perfect. And, answering myself and someone else that may ask the same question, the pictures are stored in the SD card (obviously...).
I noticed that if I set a 1 second interval, the camera is not able to take all the frames, it miss like 50% of them... I've read somewhere that this may be a problem with the firmware, there is a new version actually for the a6000 (the 1.10 I found here: http://esupport.sony.com/US/p/swu-download.pl?mdl=ILCE6000&upd_id=10073&os_group_id=5) but I haven't tested it yet. If this makes the camera faster in this mode (maybe the guys behind the software create something like a buffer or something so the machine would be able to take the pictures and shove them into a buffer and another thread would be saving them to the SD... I don't really know, it is just a wish, hehe...)
As soon as I can test the new firmware, I let you know if this issue is solved or not. Otherwise, just, try not to use those delay framerrate, probably the minimun would be 3 seconds interval (it may depend on the file size and the SD card quality, mine is not good, I am waiting for a new class 10 one with 80 mbps transfer speed).
Thank you everyone!

**Comment by retracked** [comment]
Never mind, its not a waste of time if you report bugs ;)
It is quite strange that the app does not take pictures in certain shooting modes, i'll test that with my NEX-6.

Regarding a short delay time: I created a pull request yesterday to solve this partially. The app will then wait for the camera to take and save the picture and only after that take the next one.

But even with this solution you won't be able to use shorter delay times than camera takes to save the picture. I see no way to use a "serial shooting" like behaviour with the interface Sony is giving us for the NEX and Alpha ILCEs (which would be save the picture in background while taking a new one).

**Comment by retracked** [comment]
On my NEX-6 the modes Scenery, Panorama and iA+ are disabled while using the "Smart Remote" app. When i try to choose those in the app it doesn't work. If one of those modes is selected and i start the app i get a message to change the mode. So with my camera i see no problems.

Is it different on the A6000?

**Comment by supermarcos** [comment]
Not sure from memory if are the same modes, probably very similar. That's the thing: it is not your app's bug or anything, it is just that the sony camera firmware does not allow to use certain modes for a time-lapse. But all fine anyway. There is always alternatives to get the right shoot or the closest one.
Thanks for your time, retracked!

**Comment by retracked** [comment]
Okay, thanks for the feedback. Then i'll close this issue since support for A6000 was added in Version 2.0.2.

**Comment by devzsolt** [comment]
Hi @retracked, version 3.0.1 on LineageOS 14.1 (Android 7.1) seems like not working with A6000, connects properly but then can't give instructions to the camera and receive image. I just updated Smart Remote Control app on the camera to ver 4.30
How can I help you to make it work? Thanks
