### ISSUE TITLE
RX10 long exposure

### ISSUE THREAD

**Issue by fjp** [ThibaudM/timelapse-sony#7]
Camera set to manual mode, long exposure: 15" to 30" but the app takes only images with short exposures

**Comment by retracked** [comment]
The app should not influence the camera sided settings. Does the real exposure vary? E.g. you set it to 15s and it gives you 3s in one case and 4s in another? (The exif data of the image should contain the effective exposure)

As in the other issue: are you using the latests firmware and updates?

**Comment by fjp** [comment]
Latest firmware, version 2.0, installed on camera.
I tried it again in manual mode with 2" and 5 seconds between each image in the android app.
Each image showed 1/20 exposure time.
Next I tried with 4" and 8 seconds interval. Exif data showed 1/30.
And the last test was 5" and 10 seconds interval. Also 1/30
I noticed also that the aperture time changed from 5.6 what I set, to 2.8 and ISO from 200 to 800. Once image showed to 640.

**Comment by retracked** [comment]
How exactly do you set the exposure? I watched a video on youtube and there the user could not even change any settings when in "ctrl w/ smartphone" mode. Apparently this is the same with RX100 mk2.

So it seems to me that the camera wil auto expose and you need a smartphone app that can change the settings - a thing this app unfortunately can't do until now.

So i'll close this issue for now since this would need a major redesign of the app. Sorry.
